name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: nvim-laurel
          bump-minor-pre-major: true
