name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  release-pr:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: nvim-laurel
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
