name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  vimdoc:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      # Note: Generate vimdocs only if helptags make sense.
      - name: Generate vimdoc (reference)
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: laurel-reference
          pandoc: docs/reference.md
          version: "Neovim >= 0.9.5"
          description: "Reference of nvim-laurel"
          demojify: true
          treesitter: true
          dedupsubheadings: false # Add heading to subheading anchor links to ensure that subheadings are unique
          docmapping: true # Use h4 headers as mapping docs
      - name: Generate vimdoc (cookbook)
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: laurel-cookbook
          pandoc: docs/cookbook.md
          version: "Neovim >= 0.9.5"
          description: "Cookbook of nvim-laurel"
          demojify: true
          treesitter: true
          dedupsubheadings: false # Add heading to subheading anchor links to ensure that subheadings are unique
          docmapping: false # Use h4 headers as mapping docs
      - name: Generate vimdoc (appendix)
        uses: kdheepak/panvimdoc@v4.0.0
        with:
          vimdoc: laurel-appendix
          pandoc: docs/appendix.md
          version: "Neovim >= 0.9.5"
          description: "Appendix of nvim-laurel"
          demojify: true
          treesitter: true
          dedupsubheadings: false # Add heading to subheading anchor links to ensure that subheadings are unique
          docmapping: false # Use h4 headers as mapping docs
      - name: PR new vimdoc
        uses: peter-evans/create-pull-request@v6
        with:
          branch: create-pull-request--branches--main--vimdoc
          title: "docs(vimdoc): auto-generate"
          body: |
            :robot: Update vimdoc
            ---
            This PR was generated with [create-pull-request](https://github.com/peter-evans/create-pull-request).
          commit-message: "docs(vimdoc): auto-generate"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          delete-branch: true
  release-pr:
    needs: vimdoc
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json
