name: Release
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main
jobs:
  vimdoc:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate vimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: laurel
          pandoc: doc/laurel.md
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
  release-pr:
    needs: vimdoc
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: nvim-laurel
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
