name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim_version:
          - v0.9.5
          - v0.10.4
          - v0.11.3
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - name: Install luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
      - name: Install test dependencies in Luarocks
        run: |
          sudo luarocks --lua-version=5.1 install fennel
          sudo luarocks --lua-version=5.1 install vusted
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Run tests
        run: make test
