name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nvim_version:
          - v0.9.5
          - v0.10.4
          - v0.11.3
          - stable
          - nightly
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install luarocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.1 luarocks
      - name: Install test dependencies in Luarocks
        run: |
          sudo luarocks --lua-version=5.1 install fennel
          sudo luarocks --lua-version=5.1 install vusted
      - uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        id: vim
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}
      - name: Run tests
        run: make test
